var a=5, b=4, sum=a+b;
console.log(sum);
var negInteger = -3.14159265359;
var escQuote = "Quotes can also be \"escaped\".";
var theSunIsWarm = true;
var emptyInside = null;
var justAnotherVariable;
console.log(typeof(sum));
console.log(typeof(escQuote));
console.log(typeof(theSunIsWarm));
console.log(typeof(emptyInside));
console.log(typeof(justAnotherVariable));
